services:
  backend:
    container_name: wayshub-be
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    restart: always
    networks:
      local:
    depends_on:
      - db
    ports:
      - "5001:5000"
