services:
  backend:
    container_name: wayshub-backend-production
    build:
      context: .
      dockerfile: Dockerfile
    image: backend:latest
    restart: always
    ports:
      - "5001:5000"
